name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android
        run: sdkmanager 'platforms;android-35' 'build-tools;35.0.0'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Gerar APK
        working-directory: SimplifiqueRotas-fonte/SimplifiqueRotas
        run: gradle --no-daemon :app:assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Simplifique-Rotas-APK
          path: SimplifiqueRotas-fonte/SimplifiqueRotas/app/build/outputs/apk/debug/app-debug.apk
